### ISSUE TITLE
集成Apache ShenYu网关失败

### ISSUE THREAD

**Issue by zhaorx** [uncarbon97/helio-cloud#33]
按照文档中"集成 Apache ShenYu 网关"进行操作,进行到步骤3.3-启动admin-api步骤下,没有得到文档中的结果,shenyu admin中元数据没有admin-api, 而且我看shenyu网关有admin服务和bootstrap服务, bootstrap服务不是必要的么?

**Comment by uncarbon97** [comment]
我编写文档时用的是2.5.0的shenyu，可以拉取特定版本的shenyu试一下

shenyu网页后管理要启用 springCloud 插件；
`admin-api`源码里也要引入 **shenyu-spring-boot-starter-client-springcloud** ，配置文件`admin-api.yml` 中加入
（这一块官方改了文档地址到 https://shenyu.apache.org/zh/docs/user-guide/proxy/spring-cloud-proxy/ ，回头我也更新一下我这边的文档链接）

```
shenyu:
  register:
    # 用默认的 HTTP 方式注册即可
    registerType: http #zookeeper #etcd #nacos #consul
    # shenyu-admin 地址
    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      # shenyu-admin 用户名
      username: admin
      # shenyu-admin 密码
      password: 123456
  client:
    springCloud:
      props:
        # 这里用微服务模块本名可以，当然用`/admin`也可以，决定了注册到 shenyu 后的路由前缀
        contextPath: /admin-api
        addPrefixed: false
        isFull: true
```
